spring.application.name=BankingApplication

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/novapay_db?useSSL=false&serverTimezone=Asia/Kolkata&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
 
# JWT
jwt.secret=novaPaySuperSecretKey2024novaPaySuperSecretKey2024
jwt.expiration=86400000
 
# Mail (use Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=prasadmoturi2002@gmail.com
spring.mail.password=dldhyhqhmtfabxxo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
 
# Server
server.port=8080
 
# CORS
app.cors.allowed-origins=http://localhost:3000